### ISSUE TITLE
Добавить CSS-переменные для обозначения цветов сайта.

### ISSUE THREAD

**Issue by Anastacia-Tesli** [cohorts51-52/lubimovka#23]

**Comment by egtalovikov** [comment]
https://www.figma.com/proto/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?page-id=822%3A11417&node-id=834%3A12347&viewport=11728%2C2764%2C1.1076146364212036&scaling=min-zoom&starting-point-node-id=859%3A13873&hide-ui=1

Я думаю, только на эти нужно

**Comment by egtalovikov** [comment]
На другие параметры шрифта, я думаю, не нужно, потому что они не изменятся. А цвета нужны, чтобы в случае чего быстро перейти на темный фон, например.
